name: poketap
description: Pokemon Game built with Flutter
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flame: ^0.11.2

dev_dependencies:
  flutter_launcher_icons: "^0.7.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/pikachu.png
    - assets/images/bg.jpg
  fonts:
    - family: Arcade
      fonts:
        - asset: assets/fonts/Arcade_Classic.ttf
    - family: Orange Kid
      fonts:
        - asset: assets/fonts/Orange_Kid.ttf
