name: poketap
description: Pokemon Game built with Flutter
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flame: ^0.11.2
  shared_preferences: ^0.5.1+2

dev_dependencies:
  flutter_launcher_icons: "^0.7.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/pikachu.png
    - assets/images/pikachu-active.png
    - assets/images/bg.png
    - assets/audio/pikachu.ogg
    - assets/audio/bg.mp3
    - assets/images/title.png
    - assets/images/start.png
    - assets/images/gameOver.png
  fonts:
    - family: Arcade
      fonts:
        - asset: assets/fonts/Arcade_Classic.ttf
